name: build nodejs docker image for Pterodactyl
on:
  push:
    branches: [ master ]
jobs:
  push:
    name: "thomas-docker-image:nodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 17
          - 18
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.reposirory_owner }}
          password: ${{ secrets.DOCKER_PWD }}

      - uses: docker/build-push-action@v2
        with:
          context: ./nodejs
          file: ./nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.reposirory_owner }}/pterodactyl:nodejs_${{ matrix.tag }}

